version: '1'

services:
  astra_cesbo_server:
    image: astra_raw:latest
    network_mode: "host"
    volumes:
      - ./etc/astra/license.txt:/etc/astra/license.txt
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true  