version: '1'

services:
  astra_cesbo_server:
    image: astra_cesbo_server:latest
    network_mode: "host"
    ports:
      -"8000:8000"
    volumes:
    - type: bind
      source: ./etc/astra
      target: /etc/astra
      