version: '1'

services:
  astra_cesbo_server:
    image: astra_cesbo_server:latest
    network_mode: "host"
    ports:
      -"8000:8000"
    volumes:
      - /home/astra/astra_server/etc/astra/: /etc/astra/
volumes:
/home/astra/astra_server/etc/astra/
